use_frameworks!

target 'TPSDropDown_Example' do
    pod 'TPSDropDown', :path => '../'

    target 'TPSDropDown_Tests' do
        inherit! :search_paths
        pod 'FBSnapshotTestCase', '~> 2.1'
        pod 'TPSDropDown', :path => '../'
    end
end
